### PR TITLE
fix: fixing create_comment function

### PR DESCRIPTION
**Pull request by 2yaty**

### CODE REVIEW

**Comment by ziadhany** [comment]
@2yaty can you edit the error pages  `error_500.html , error_404.html`?

**Comment by 2yaty** [comment]
> @2yaty can you edit the error pages `error_500.html , error_404.html`?

yes, I can sir, any thing else?  ;D

**Comment by ziadhany** [comment]
> > @2yaty can you edit the error pages `error_500.html , error_404.html`?
> 
> yes, I can sir, any thing else? ;D

can you write some test ?

**Comment by 2yaty** [comment]
> > > @2yaty can you edit the error pages `error_500.html , error_404.html`?
> > 
> > 
> > yes, I can sir, any thing else? ;D
> 
> can you write some test ?

not that level ya 2m el 7ag

**Comment by ziadhany** [comment]
@2yaty 
can you drop this utils.py commit  [6503ccf](https://github.com/ziadhany/simple_blog/pull/3/commits/6503ccfd7e383fd08f47f9264c8759d036cedbf2)?

**Pull request closed without merging**
